In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


To see the type of data

In [3]:
print(type(arr1))

<class 'numpy.ndarray'>


To see the shape (How many values within the variable)

In [5]:
print(arr1.shape)

(5,)


Check the value with in the variable at **index 4**

In [6]:
print(arr1[4])  # Index starts from 0

5


To change the value at **index 3** to '9'

In [7]:
arr1[3] = 9     # Update the 4th element
print(arr1)

[1 2 3 9 5]


If I want to change the whole array (2D Array)

In [8]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


To get specific values from 2D arrays

In [9]:
arr2[0, 2]

np.int64(3)

In [10]:
print(arr2.shape)

(2, 3)


Fetching values using negetive indexing

In [11]:
arr2[1][-2]

np.int64(5)

In [15]:
arrC = (['India', 'Canada', 'USA', 'Australia', 'Germany'])
print(arrC)
print(type(arrC))
print(np.shape(arrC))

['India', 'Canada', 'USA', 'Australia', 'Germany']
<class 'list'>
(5,)


To create a list starting with '0' upto '29' with a increment of '3'

In [16]:
arrM = np.arange(0, 30, 3)
print(arrM)

[ 0  3  6  9 12 15 18 21 24 27]


To generate an array of evenly spaced numbers

In [17]:
arrL = np.linspace(0, 5, 10)  # 10 values between 0 and 5
print(arrL)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [18]:
arrL = np.linspace(0, 15, 30)  # 30 values between 0 and 15
print(arrL)

[ 0.          0.51724138  1.03448276  1.55172414  2.06896552  2.5862069
  3.10344828  3.62068966  4.13793103  4.65517241  5.17241379  5.68965517
  6.20689655  6.72413793  7.24137931  7.75862069  8.27586207  8.79310345
  9.31034483  9.82758621 10.34482759 10.86206897 11.37931034 11.89655172
 12.4137931  12.93103448 13.44827586 13.96551724 14.48275862 15.        ]


If you need an array with random values

In [19]:
arr = np.random.rand(8)  # 1D array with 8 random values
print(arr)

[0.37533187 0.30452614 0.85272536 0.9773384  0.18917398 0.36625272
 0.70998938 0.63565519]


In [20]:
arr = np.random.rand(3, 4)  # 2D array with 3 rows and 4 columns
print(arr)

[[0.012216   0.07695676 0.85718019 0.46209002]
 [0.85512558 0.312086   0.27988817 0.47190132]
 [0.1180261  0.35616159 0.39235256 0.678522  ]]


To cerate random values with 0 or 1

In [23]:
print(np.zeros(8))
print('/y')
print(np.zeros((3,4)))

[0. 0. 0. 0. 0. 0. 0. 0.]
/y
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
print(np.ones((4,2,4))) # 3D array with 4 blocks, each having 2 rows and 4 columns

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [26]:
arr = [0,1,2, 'India', 'A']
print(np.repeat(arr, 3))  # Repeat each element 3 times

['0' '0' '0' '1' '1' '1' '2' '2' '2' 'India' 'India' 'India' 'A' 'A' 'A']
