In [1]:
import numpy as np

In [2]:
arr = np.random.rand(6,6)
arr

array([[0.74908584, 0.36527563, 0.6804576 , 0.93548156, 0.3165882 ,
        0.45332206],
       [0.90619284, 0.7158485 , 0.87640358, 0.83171124, 0.11948785,
        0.81107997],
       [0.47537691, 0.4904391 , 0.33953006, 0.02208506, 0.28487514,
        0.67149401],
       [0.28775423, 0.21071023, 0.16388172, 0.9929103 , 0.54501644,
        0.87516209],
       [0.09550449, 0.11748007, 0.1395661 , 0.98635679, 0.02694974,
        0.69967652],
       [0.7955236 , 0.97914897, 0.06741601, 0.72122694, 0.7800436 ,
        0.1062415 ]])

In [5]:
np.diag(arr)  # Extract the diagonal elements

array([0.74908584, 0.7158485 , 0.33953006, 0.9929103 , 0.02694974,
       0.1062415 ])

In [6]:
arr.ndim        # Number of dimensions

2

In [7]:
arr.size       # Total number of elements (6*6 = 36)

36

In [8]:
arr.shape

(6, 6)

In [9]:
np.random.randint(-5, 5, 2)  # Random integers between -5 and 5 (exclusive), shape (2,)

array([4, 4], dtype=int32)

In [ ]:
np.random.randint(-5, 39, 10) # Random integers between -5 and 39 (exclusive), shape (10,)

array([ 3, 23,  6, 22, -3, 10, 31,  1,  9, 26], dtype=int32)

In [ ]:
arr/3 # Element-wise division by 3

array([[0.24969528, 0.12175854, 0.2268192 , 0.31182719, 0.1055294 ,
        0.15110735],
       [0.30206428, 0.23861617, 0.29213453, 0.27723708, 0.03982928,
        0.27035999],
       [0.15845897, 0.1634797 , 0.11317669, 0.00736169, 0.09495838,
        0.22383134],
       [0.09591808, 0.07023674, 0.05462724, 0.3309701 , 0.18167215,
        0.2917207 ],
       [0.03183483, 0.03916002, 0.04652203, 0.3287856 , 0.00898325,
        0.23322551],
       [0.26517453, 0.32638299, 0.022472  , 0.24040898, 0.26001453,
        0.03541383]])

In [12]:
np.exp(arr) # Element-wise exponentiation of e

array([[2.11506561, 1.44091112, 1.97478118, 2.5484404 , 1.37243728,
        1.57353088],
       [2.4748823 , 2.0459219 , 2.40224466, 2.29724652, 1.12691955,
        2.25033697],
       [1.6086204 , 1.63303312, 1.4042875 , 1.02233074, 1.329596  ,
        1.95715916],
       [1.33342955, 1.23455456, 1.17807497, 2.69907817, 1.72463674,
        2.39926415],
       [1.10021377, 1.12465922, 1.14977481, 2.68144759, 1.02731617,
        2.0131014 ],
       [2.21560077, 2.66218967, 1.0697404 , 2.05695543, 2.18156739,
        1.11209041]])

In [13]:
np.log(arr) # Element-wise natural logarithm

array([[-0.2889017 , -1.00710305, -0.38498977, -0.06669384, -1.15015341,
        -0.79115246],
       [-0.09850315, -0.33428673, -0.13192859, -0.18426997, -2.12454057,
        -0.20938862],
       [-0.74364728, -0.71245418, -1.0801928 , -3.81285396, -1.25570431,
        -0.39825018],
       [-1.24564853, -1.55727142, -1.8086103 , -0.00711496, -0.60693931,
        -0.13334617],
       [-2.34858198, -2.14148654, -1.96921693, -0.01373713, -3.61378163,
        -0.35713717],
       [-0.22875477, -0.02107148, -2.69687282, -0.32680143, -0.24840546,
        -2.24204047]])

In [14]:
np.log2(arr) # Element-wise base-2 logarithm

array([[-0.41679705, -1.45294258, -0.55542283, -0.09621887, -1.65932063,
        -1.14139172],
       [-0.14211   , -0.48227381, -0.19033272, -0.26584537, -3.06506415,
        -0.30208393],
       [-1.07285625, -1.02785411, -1.55838879, -5.5007855 , -1.81159838,
        -0.57455356],
       [-1.79709096, -2.24666775, -2.60927312, -0.01026471, -0.87562834,
        -0.19237785],
       [-3.38828758, -3.08951202, -2.84097951, -0.01981849, -5.21358483,
        -0.51524002],
       [-0.33002337, -0.03039973, -3.89076504, -0.47147481, -0.35837332,
        -3.23458067]])

In [16]:
np.log10(arr) # Element-wise base-10 logarithm

array([[-0.12546842, -0.4373793 , -0.16719893, -0.02896477, -0.49950528,
        -0.34359315],
       [-0.04277937, -0.14517888, -0.05729586, -0.08002743, -0.92267625,
        -0.09093632],
       [-0.32296191, -0.30941492, -0.46912177, -1.65590143, -0.54534545,
        -0.17295786],
       [-0.54097828, -0.67631438, -0.78546948, -0.00308999, -0.2635904 ,
        -0.0579115 ],
       [-1.0199762 , -0.93003579, -0.85522005, -0.00596596, -1.56944542,
        -0.1551027 ],
       [-0.09934693, -0.00915123, -1.17123698, -0.14192806, -0.10788112,
        -0.97370581]])

In [17]:
np.tan(arr)     # Element-wise tangent

array([[0.92989037, 0.38243797, 0.80941849, 1.35632465, 0.32760718,
        0.4871589 ],
       [1.27631155, 0.86974947, 1.20084343, 1.09719716, 0.12005977,
        1.05272939],
       [0.51474881, 0.5339523 , 0.35320822, 0.02208865, 0.29284003,
        0.79468881],
       [0.29596866, 0.21388505, 0.16536479, 1.53338664, 0.60626918,
        1.1978162 ],
       [0.09579593, 0.11802354, 0.14047941, 1.51164226, 0.02695627,
        0.84173556],
       [1.02045872, 1.4882189 , 0.06751832, 0.879241  , 0.98934782,
        0.10664304]])

In [ ]:
np.sum(arr)  # Sum of all elements

np.float64(18.635304490005286)

In [23]:
np.sum(arr, axis = 0)  # Sum along the first axis (columns)

array([3.30943791, 2.8789025 , 2.26725507, 4.4897719 , 2.07296097,
       3.61697615])

In [24]:
np.sum(arr, axis = 1)  # Sum along the second axis (rows)

array([3.50021089, 4.26072397, 2.28380028, 3.07543501, 2.06553372,
       3.44960062])

In [ ]:
np.mean(arr) # Mean of all elements

np.float64(0.5176473469445912)

In [21]:
np.std(arr)  # Standard deviation

np.float64(0.32129734445795183)

In [25]:
np.min(arr)  # Minimum element

np.float64(0.02208505911032077)

In [26]:
np.max(arr)  # Maximum element

np.float64(0.9929102958396305)

In [27]:
np.min(arr, axis=0)  # Minimum along the first axis (columns)

array([0.09550449, 0.11748007, 0.06741601, 0.02208506, 0.02694974,
       0.1062415 ])

In [28]:
np.min(arr, axis=1)  # Minimum along the second axis (rows)

array([0.3165882 , 0.11948785, 0.02208506, 0.16388172, 0.02694974,
       0.06741601])

In [29]:
arr[1:3:1]  # Slicing from index 1 to 3 (exclusive) with step 1

array([[0.90619284, 0.7158485 , 0.87640358, 0.83171124, 0.11948785,
        0.81107997],
       [0.47537691, 0.4904391 , 0.33953006, 0.02208506, 0.28487514,
        0.67149401]])

In [ ]:
a = np.random.randint(1, 10, 5) # Random array of 5 integers from 1 to 9
print(a)

[7 8 9 1 9]


In [34]:
a[1:3:1] # Slicing from index 1 to 3 (exclusive) with step 1

array([8, 9], dtype=int32)

In [36]:
a[1:3:-1] # Slicing from index 1 to 3 (exclusive) with step -1

array([], dtype=int32)

In [37]:
np.sort(a)

array([1, 7, 8, 9, 9], dtype=int32)

In [38]:
arr.T # Transpose of the array

array([[0.74908584, 0.90619284, 0.47537691, 0.28775423, 0.09550449,
        0.7955236 ],
       [0.36527563, 0.7158485 , 0.4904391 , 0.21071023, 0.11748007,
        0.97914897],
       [0.6804576 , 0.87640358, 0.33953006, 0.16388172, 0.1395661 ,
        0.06741601],
       [0.93548156, 0.83171124, 0.02208506, 0.9929103 , 0.98635679,
        0.72122694],
       [0.3165882 , 0.11948785, 0.28487514, 0.54501644, 0.02694974,
        0.7800436 ],
       [0.45332206, 0.81107997, 0.67149401, 0.87516209, 0.69967652,
        0.1062415 ]])

In [39]:
arr[:2, :].T    # Transpose of the first two rows

array([[0.74908584, 0.90619284],
       [0.36527563, 0.7158485 ],
       [0.6804576 , 0.87640358],
       [0.93548156, 0.83171124],
       [0.3165882 , 0.11948785],
       [0.45332206, 0.81107997]])

In [41]:
arr[:2, :4].T   # Transpose of the first two rows and first four columns

array([[0.74908584, 0.90619284],
       [0.36527563, 0.7158485 ],
       [0.6804576 , 0.87640358],
       [0.93548156, 0.83171124]])

In [42]:
arr[ : 2, : ].flatten()     # Flatten the first two rows

array([0.74908584, 0.36527563, 0.6804576 , 0.93548156, 0.3165882 ,
       0.45332206, 0.90619284, 0.7158485 , 0.87640358, 0.83171124,
       0.11948785, 0.81107997])

In [ ]:
arr[:2, :].transpose() # Transpose of the first two rows    #  Same as arr[:2, :].T

array([[0.74908584, 0.90619284],
       [0.36527563, 0.7158485 ],
       [0.6804576 , 0.87640358],
       [0.93548156, 0.83171124],
       [0.3165882 , 0.11948785],
       [0.45332206, 0.81107997]])

In [45]:
arr = np.array([5,6,7,8,9])
arr

array([5, 6, 7, 8, 9])

In [ ]:
arr1 = np.append(arr, 7) # Append 7 to the array
arr1

array([5, 6, 7, 8, 9, 7])

In [ ]:
arr2 = np.insert(arr, 0, [1,2,3]) # Insert 1, 2, 3 at the beginning; index 0
arr2

array([1, 2, 3, 5, 6, 7, 8, 9])

In [ ]:
arr3 =np.delete(arr2,[]) # Delete elements at specified indices; here, no indices are specified, so no deletion occurs
arr3

array([1, 2, 3, 5, 6, 7, 8, 9])

In [ ]:
arr4 =np.delete(arr2,[2]) # Delete element at index 2
arr4

array([1, 2, 5, 6, 7, 8, 9])

In [55]:
arr5 = np.delete(arr4,[0,1]) # Delete elements at indices 0 and 1
arr5

array([5, 6, 7, 8, 9])

In [ ]:
arrG = arr3.copy()  # Create a copy of arr3
arrG

array([1, 2, 3, 5, 6, 7, 8, 9])

Concatenating Arrays

In [ ]:
arr_concat = np.concatenate((arr1, arr2, arr3, arr4, arr5, arrG))
arr_concat

array([5, 6, 7, 8, 9, 7, 1, 2, 3, 5, 6, 7, 8, 9, 1, 2, 3, 5, 6, 7, 8, 9,
       1, 2, 5, 6, 7, 8, 9, 5, 6, 7, 8, 9, 1, 2, 3, 5, 6, 7, 8, 9])

In [60]:
a = np.array([[1,2,3,],[4,5,6]])
b = np.array([[6,5,4],[3,2,1]])

c = np.concatenate((a,b))
print(c)

[[1 2 3]
 [4 5 6]
 [6 5 4]
 [3 2 1]]


In [63]:
d = np.concatenate((a,b), axis = 0)  # Concatenate along the first axis (rows)
print(d)

[[1 2 3]
 [4 5 6]
 [6 5 4]
 [3 2 1]]


In [64]:
e = np.concatenate((a,b), axis = 1)  # Concatenate along the second axis (columns)
print(e)

[[1 2 3 6 5 4]
 [4 5 6 3 2 1]]


V Stack

In [67]:
x = np.vstack((a,b))  # Vertical stack
print(x)

y = np.hstack((a,b))  # Horizontal stack
print('\n', y)

[[1 2 3]
 [4 5 6]
 [6 5 4]
 [3 2 1]]

 [[1 2 3 6 5 4]
 [4 5 6 3 2 1]]
