In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 1, 2, 3])
np.unique(a)  # Find unique elements

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
np.unique(a, return_counts=True)  # Find unique elements and their counts

(array([1, 2, 3, 4, 5, 6, 7]), array([2, 2, 2, 1, 1, 1, 1]))

In [4]:
uniques, counts = np.unique(a, return_counts=True)
print(uniques)
print(counts)

[1 2 3 4 5 6 7]
[2 2 2 1 1 1 1]


In [6]:
a = np.array([1,2,3,4])
b = np.array([3,4,5,6])

print(np.intersect1d(a,b))  # Intersection of two arrays
print(np.setdiff1d(a,b))  # Elements in a but not in b
print(np.setdiff1d(b,a))  # Elements in b but not in a
print(np.union1d(a,b))  # Union of two arrays
print(np.setxor1d(a,b))  # Elements in either a or b but not in both

[3 4]
[1 2]
[5 6]
[1 2 3 4 5 6]
[1 2 5 6]
